### ISSUE TITLE
bug: paste in list don't work well

### ISSUE THREAD

**Issue by Jackiexiao** [esm7/obsidian-vimrc-support#11]
see gif 
![bug-vim-paste](https://user-images.githubusercontent.com/18050469/103260204-dc6f2580-49d7-11eb-9695-8f1d8e2da7c7.gif)

**Comment by esm7** [comment]
Thanks for taking the time to show this.
I was unable to recreate the issue, so maybe there are other factors causing it. What version of Obsidian are you using?
Also, is the issue affected by whether the Vimrc plugin is enabled?
If it also happens when the plugin is disabled, I suggest to try recreating it in the [CodeMirror Vim demo](https://codemirror.net/demo/vim.html). If it happens there, it's a CodeMirror issue and should be reported [here](https://github.com/codemirror/CodeMirror/issues). Otherwise it's an Obsidian issue and should be reported in the Obsidian forum under bug reports.

**Comment by Jackiexiao** [comment]
thx for your time! I use obsidian v0.10.2, I think this bug is not relevant with obsidian-vimrc-support, I will reported it in Obsidian forum

**Comment by Jackiexiao** [comment]
I have confirmed that this is a bug in obsidian-vimrc-support, with `.obsidian.vimrc` set to `set clipboard=unnamed`, if you paste many times, you could reproduce it. when there is nothing in `.obsidian.vimrc`, everything works fine

**Comment by esm7** [comment]
Great find! I'll use that to investigate.

**Comment by Jackiexiao** [comment]
hi! any progress? can you reproduce the bug?

**Comment by esm7** [comment]
Unfortunately I couldn't find the time to work on this (or any other plugin-related topics). Hoping to get to it soon enough.

**Comment by Jackiexiao** [comment]
thx for your reply, take your time!!

**Comment by esm7** [comment]
I tried spending some time on this, and while I was unable to recreate the issue, I did come up with a theory of how it might possible happen on some platforms.
Do you mind testing a potential fix by unzipping it to the plugin directory under VAULT/.obsidian/plugins/PLUGIN_NAME?
If you do happen to make the issue recreate with this version, there are some debug prints added, and I could use those from your Obsidian developer console (Ctrl+Shift+I).
[obsidian-vimrc.zip](https://github.com/esm7/obsidian-vimrc-support/files/5843767/obsidian-vimrc.zip)

**Comment by tadashi-aikawa** [comment]
I have encountered this problem too.
When I used `obsidian-vimrc.zip` above, it seems to be work fine for my environment (Windows10 and Obsidian v0.10.8) 😄

**Comment by Jackiexiao** [comment]
Windows10 and Obsidian v0.10.9 works fine!! thx @esm7

**Comment by esm7** [comment]
That's great news. So I wrapped it in a formal release (0.2.4).
