### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by jin-ahn** [esm7/obsidian-vimrc-support#171]
**Please make sure this feature request is within the scope of this plugin.**

- [X] I understand that if my request is about supporting some Vim feature, it probably belongs [here](https://github.com/replit/codemirror-vim).

**Describe the feature that you'd like:**

The recent obsidian mobile updated added vim support for mobile versions (ie ipados and iOS). This plugin is listed as supported but I am not able to get my existing .obsidian.vimrc to work. It might the limitation that in iPadOS no files are allowed to start with ".". I've tested with making a separate file that does not start with "." But it still does not seem to get recognized.

**Additional context:**

**Comment by StefanoRausch** [comment]
Same here. my ".vimrc" file works fine with the desktop version but fails to load on the iPad / iPhone.

I started using the VIM keybindings a few days ago -- still learning the ropes -- and I would love to use your plugin on the mobile app.

**Comment by StefanoRausch** [comment]
> Same here. my ".vimrc" file works fine with the desktop version but fails to load on the iPad / iPhone.
> 
> I started using the VIM keybindings a few days ago -- still learning the ropes -- and I would love to use your plugin on the mobile app.

I have found a solution by renaming the ".vimrc" file to "vim.rc". Now the remappings do work on all my devices!

**Comment by jwhitley** [comment]
Agreed with other commenters. My process was:
1. Change this plugin's setting for the vimrc file to `obsidian.vimrc` (no leading dot)
2. Renamed my vimrc file to match
3. Restarted the desktop app and confirmed it was working
4. Ensure sync from desktop has happened (e.g. via Sync log)
5. Sync config and vimrc change to iPad
6. Quit/restart the iPad app to ensure this plugin has reloaded the updated vimrc

It works as expected after that, on both desktop and iPad.

This issue seems to be "fix by documentation", ideally right in the README.

**Comment by jin-ahn** [comment]
> Agreed with other commenters. My process was:
> 
> 1. Change this plugin's setting for the vimrc file to `obsidian.vimrc` (no leading dot)
> 2. Renamed my vimrc file to match
> 3. Restarted the desktop app and confirmed it was working
> 4. Ensure sync from desktop has happened (e.g. via Sync log)
> 5. Sync config and vimrc change to iPad
> 6. Quit/restart the iPad app to ensure this plugin has reloaded the updated vimrc
> 
> It works as expected after that, on both desktop and iPad.
> 
> This issue seems to be "fix by documentation", ideally right in the README.
