### ISSUE TITLE
VIM Surround Function will sometimes place brackets at a different position than the current selection

### ISSUE THREAD

**Issue by brandonkboswell** [esm7/obsidian-vimrc-support#39]
Here is a Loom of an issue I am experiencing where the vim-surround gets out of sync over time. Quitting out of Obsidian and reopening the page fixes whatever is causing this.

https://www.loom.com/share/c58db6c70ce149aab06ca00f67d76d8b

**Comment by Andr3wD** [comment]
I spent some time looking into it and couldn't replicate the problem, but I can explain why this might happen. CodeMirror's (CM) vim mode doesn't actually allow normally obtaining of the cursor selections, for some reason (bug). But the `cursorActivity` CM event for some reason can get the cursor position, so the position is recorded on `cursorActivity` and used for the surround command. CM is likely accidentally keeping multiple selections due to a bug somewhere else in CM. I've made changes to attempt to fix the bug in 89219379865ca1ed306138d1fa60c51ad6e1df2b and have made a PR #41, but I'd like to get @esm7's thoughts as well.
