### ISSUE TITLE
jj imap to <Esc> not work ?

### ISSUE THREAD

**Issue by philipjin** [esm7/obsidian-vimrc-support#4]
I have created a simple .obsidian.vimrc , but  seems the following jj map esc not work. 
Any special configuration needs tune ?  Plugin already enabled.

nmap <leader><space> :noh<cr> 
imap jj <Esc>

❯ ll .obsidian.vimrc
.rw-r--r-- 45 pp  2 Dec 17:38 .obsidian.vimrc

**Comment by kofm** [comment]
Was just checking the issues because i had the same problem
it works only if you use <Esc> (case sensitive) 
like so:

`imap fd <Esc>`

**Comment by iaso2h** [comment]
Revise it to `imap jj <Esc>` should do the trick.

**Comment by philipjin** [comment]
thanks guys , for some reason , when I copy paste from my iterm2 to github , the "<Esc>" lost.  after delete the first line , only keep 'imap jj <Esc>' , and restart obsidian . It worked !  Will migrate other shutcuts . Please mark it closed!

**Comment by philipjin** [comment]
The `<Esc>` part could be treat as an XSS , so can't directly be put into the comment area.

**Comment by RiccardoTonioloDev** [comment]
Hey, I have the same problem and nothing suggested seems to work.
I am using `imap jk <Esc>`.

**Comment by hf** [comment]
Same here.

**Comment by RiccardoTonioloDev** [comment]
> Same here.

I've solved the problem. Tell me if you need help.

**Comment by vavrav03** [comment]
> > Same here.
> 
> I've solved the problem. Tell me if you need help.

How did you solve it?

**Comment by tusharsnn** [comment]
@RiccardoTonioloDev can you tell us how solved this?

**Comment by RiccardoTonioloDev** [comment]
Sorry @tusharsnn and @vavrav03 . Basically all you need to do if you are on a Mac or Linux machine is:
- In your obsidian vault, the directory where you can find the `.obsidian` folder: create the `.obsidian.vimrc` file;
- In the `.obsidian.vimrc` file, write the following command: `imap jk <Esc>`.

Be carefull tho: for me the problem was the editing of the file. Basically if you edit the file with the base notepad app of macOS, it will add (idk why) strange chars at the beginning of the file. My suggestion is to locate the vault folder in the terminal; to create the file using `touch .obsidian.vimrc` as a terminal command; and then use vim, nvim or vi to edit the text file in order to add the `imap` command.

**Comment by Laurensdc** [comment]
The default folder to put `.obsidian.vimrc` is in the root of your vault, not in the `.obsidian` folder.

**Comment by zyfyy** [comment]
for my case: `imap jk <esc>` not work
turn out `imap jk <Esc>` works

**Comment by piction** [comment]
I was also struggling with having it to work because I was overlooking that the **Esc** is case sensitive.
`imap jk <Esc>`
Works for me if I put this next to the folder ".obsidian" in a file named ".obsidian.vimrc"

**Comment by sachasmart** [comment]
I am currently running into this issue. I've reloaded the app with only `imap jk <Esc>` in my `.obsidian.vimrc` file and no luck.

**Comment by zaiquiriw** [comment]
I'm committing myself to comment if there is a solution to this issue, or if it's just waiting for changes to apply or something.

**Comment by zaiquiriw** [comment]
And yup, it just took 2 minutes for the changes to take effect. No idea was the lag was strong with this one.

**Comment by Laurensdc** [comment]
The mapping works for me on my Android tablet with an external physical bluetooth keyboard, but not with the software keyboards (tried different ones). It does work on iOS. Frustrating.
