### ISSUE TITLE
command short names

### ISSUE THREAD

**Issue by pwntester** [esm7/obsidian-vimrc-support#43]
hey, thanks for the plugin, this is really enabling me to use obsidian!

This is probably a CodeMirror issue but wanted to ask here first since it may be a configuration option.

When I define a new command such as `exmap quit obcommand workspace:close` I can definitely use `:quit` but not `:q`. I can also define a similar command for `:q` but I was wondering if CodeMirror can do that. It seems that works for commands such as `:nmap` (I can type `:nma`)

Thanks!

**Comment by pwntester** [comment]
Looking at the code it seems like passing a `prefix` as the second argument to `defineEx` [here](https://github.com/esm7/obsidian-vimrc-support/blob/master/main.ts#L207) could work to define a short name. Perhaps we could introduce some notation to define a shortname in the vimrc file. But I guess that is similar to define a new command with the shorthand. Ideally CodeMirror should do this on its own 🤔

**Comment by Andr3wD** [comment]
I can see what you're talking about. As it stands, it looks like the `exmap` command won't be able to be changed so as to not break anyone's configs. A new command, say `pexmap`, could be added that takes in a prefix though. If this is something you would find especially useful then I can look into adding the new command.

Otherwise, doing something like this works:
```
exmap quit obcommand workspace:close
exmap q :quit
```
